In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import torch

### Intro to tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
vector = torch.tensor([1,2,3,4])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([4])

In [7]:
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6],])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 3])

In [10]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

In [14]:
torch.rand(3,4)

tensor([[0.5094, 0.9839, 0.9683, 0.4783],
        [0.9351, 0.6071, 0.6405, 0.6456],
        [0.8107, 0.7072, 0.1392, 0.6720]])

In [15]:
torch.rand(10,10)

tensor([[0.4837, 0.1616, 0.4678, 0.2261, 0.6404, 0.7535, 0.0552, 0.9175, 0.3741,
         0.1886],
        [0.3206, 0.7783, 0.1013, 0.1268, 0.2796, 0.5126, 0.2172, 0.0913, 0.1365,
         0.1790],
        [0.3111, 0.0573, 0.6271, 0.8695, 0.9929, 0.6200, 0.6814, 0.2218, 0.3727,
         0.0708],
        [0.2901, 0.5373, 0.5883, 0.1578, 0.2441, 0.0594, 0.4020, 0.2041, 0.6780,
         0.8761],
        [0.3594, 0.0521, 0.8448, 0.6782, 0.5807, 0.5157, 0.5551, 0.1884, 0.3109,
         0.3768],
        [0.5794, 0.2473, 0.3044, 0.0678, 0.4928, 0.7795, 0.7079, 0.5280, 0.4440,
         0.2785],
        [0.7356, 0.2706, 0.0907, 0.2175, 0.4317, 0.2949, 0.4118, 0.8979, 0.8570,
         0.5848],
        [0.5082, 0.5364, 0.7796, 0.3003, 0.2698, 0.4554, 0.1648, 0.3174, 0.4603,
         0.5509],
        [0.1515, 0.2824, 0.0876, 0.7646, 0.9189, 0.4913, 0.1556, 0.0945, 0.0109,
         0.3583],
        [0.6345, 0.2189, 0.4379, 0.1369, 0.1526, 0.4845, 0.4046, 0.9426, 0.1132,
         0.3974]])

In [16]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.9402, 0.9081, 0.0298],
         [0.1883, 0.2816, 0.6137],
         [0.1712, 0.5998, 0.2551],
         ...,
         [0.7476, 0.8078, 0.5400],
         [0.7015, 0.9258, 0.5110],
         [0.8584, 0.5207, 0.4557]],

        [[0.9520, 0.5322, 0.2519],
         [0.6212, 0.5408, 0.0998],
         [0.2574, 0.3712, 0.2162],
         ...,
         [0.9268, 0.1670, 0.8533],
         [0.2669, 0.2321, 0.4055],
         [0.4400, 0.3047, 0.0142]],

        [[0.7395, 0.9433, 0.4935],
         [0.4932, 0.2155, 0.4317],
         [0.3119, 0.4350, 0.8774],
         ...,
         [0.4260, 0.7355, 0.0838],
         [0.4125, 0.8143, 0.7588],
         [0.7341, 0.7379, 0.8566]],

        ...,

        [[0.9887, 0.2800, 0.4768],
         [0.0138, 0.8736, 0.5620],
         [0.2191, 0.7250, 0.6035],
         ...,
         [0.5184, 0.7848, 0.7468],
         [0.6289, 0.4357, 0.1716],
         [0.4878, 0.9098, 0.8949]],

        [[0.5639, 0.6903, 0.1301],
         [0.4857, 0.3917, 0.9698],
         [0.

In [17]:
torch.zeros(size=(4,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.ones(size=(5,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [20]:
one_to_twenty = torch.arange(1,21,1)

In [21]:
torch.rand_like(one_to_twenty,dtype=torch.float)

tensor([0.6203, 0.9952, 0.7744, 0.8060, 0.0892, 0.8010, 0.0053, 0.8652, 0.0542,
        0.0254, 0.6314, 0.4162, 0.0636, 0.6772, 0.9206, 0.3745, 0.9601, 0.2570,
        0.8487, 0.4144])

In [22]:
float_32_tensor = torch.tensor(data=[1.0,2.0,3.0],dtype=torch.float32,device="cuda")
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

In [24]:
float_16_tensor + float_32_tensor

tensor([2., 4., 6.], device='cuda:0')

In [25]:
result = float_32_tensor @ float_32_tensor

result = result.type(dtype=torch.uint32)
result

tensor(14, device='cuda:0', dtype=torch.uint32)

In [26]:
torch.seed()
tensor = torch.randint(1,10,size=(3,3),device="cuda")
tensor

tensor([[5, 1, 2],
        [3, 5, 5],
        [4, 2, 2]], device='cuda:0')

In [27]:
print(f"Tensor datatype: {tensor.dtype}")
print(f"Tensor shape: {tensor.shape}")
print(f"Tensor device: {tensor.device}")

Tensor datatype: torch.int64
Tensor shape: torch.Size([3, 3])
Tensor device: cuda:0


### Tensor Operation

In [28]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
tensor * 10

tensor([10, 20, 30])

In [30]:
tensor - 10

tensor([-9, -8, -7])

In [31]:
tensor @ tensor

tensor(14)

In [32]:
tensor_3x2 = torch.tensor([[1,2],
                           [3,4],
                           [5,6]])

tensor_3x2_2 = torch.tensor([[1, 2], [3, 4], [5, 6]],s)

In [33]:
tensor_3x2 @ tensor_3x2_2.T

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [34]:
torch.matmul(tensor_3x2,tensor_3x2_2.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [44]:
torch.manual_seed(101)

torch.rand(4,3)

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186],
        [0.9095, 0.3406, 0.4309],
        [0.7324, 0.4776, 0.0716]])

In [45]:
torch.matmul(torch.rand(4,3), torch.rand(3,4))

tensor([[0.7521, 1.1363, 0.8183, 0.9253],
        [0.3534, 0.7554, 0.5626, 0.7244],
        [0.7583, 0.9013, 0.6975, 0.6621],
        [0.3791, 0.4298, 0.2997, 0.2809]])

In [59]:
torch.manual_seed(42)
tensorA = torch.tensor(data=[[1, 2], [3, 4], [5, 6]],dtype=torch.float32)

linear = torch.nn.Linear(in_features=3,out_features=6,dtype=torch.float32)

x= tensorA
output= linear(x.T)
print(f"input shape: {x.shape}")
print(f"Output:\n{output} \n output shape: {output.shape} ")

input shape: torch.Size([3, 2])
Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>) 
 output shape: torch.Size([2, 6]) 


In [73]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [74]:
print(f"min x adalah: {x.min()}")
print(f"max x adalah : {x.max()}")
print(f"mean x adalah: {x.mean(dtype=torch.float32)}")
print(f"sum x adalah: {x.sum()}")

min x adalah: 0
max x adalah : 90
mean x adalah: 45.0
sum x adalah: 450


In [76]:
print(f"index min x adalah: {x.argmin()}")
print(f"index max x adalah: {x.argmax()}")

index min x adalah: 0
index max x adalah: 9
