In [56]:
import torch

In [57]:
tensor = torch.randint(1,10,size=(1,10))
tensor

tensor([[2, 8, 5, 5, 5, 9, 5, 3, 4, 3]])

In [58]:
tensor.argmax()

tensor(5)

### Reshape,Squuezing unsqueezing tensors

In [59]:
tensor.reshape(1,10)

tensor([[2, 8, 5, 5, 5, 9, 5, 3, 4, 3]])

In [60]:
tensor.reshape(2,5)

tensor([[2, 8, 5, 5, 5],
        [9, 5, 3, 4, 3]])

In [61]:
tensor.view(5,2)

tensor([[2, 8],
        [5, 5],
        [5, 9],
        [5, 3],
        [4, 3]])

In [62]:
tensor = tensor.reshape(10)

In [63]:
v_stacked = torch.stack(tensors=[tensor,tensor],dim=0)
v_stacked

tensor([[2, 8, 5, 5, 5, 9, 5, 3, 4, 3],
        [2, 8, 5, 5, 5, 9, 5, 3, 4, 3]])

In [64]:
h_stacked = torch.stack(tensors=[tensor,tensor],dim=1)
h_stacked

tensor([[2, 2],
        [8, 8],
        [5, 5],
        [5, 5],
        [5, 5],
        [9, 9],
        [5, 5],
        [3, 3],
        [4, 4],
        [3, 3]])

In [65]:
torch.hstack(tensors=[tensor,tensor])

tensor([2, 8, 5, 5, 5, 9, 5, 3, 4, 3, 2, 8, 5, 5, 5, 9, 5, 3, 4, 3])

In [66]:
tensor = torch.arange(1,11).reshape(1,10)
tensor

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [67]:
tensor = tensor.squeeze()
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
tensor.unsqueeze(dim=0)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [78]:
tensor = torch.rand(size=(24,24,3))
tensor.shape

torch.Size([24, 24, 3])

In [74]:
tensor.permute(dims=(2,0,1)).shape

torch.Size([3, 24, 24])

In [81]:
x_original = torch.rand(size=(16,16,3))
print(f"Shape x original: {x_original.shape}")

x_permuted = x_original.permute(dims=(2,0,1))
print(f"Shape x permuted: {x_permuted.shape}")

Shape x original: torch.Size([16, 16, 3])
Shape x permuted: torch.Size([3, 16, 16])


In [86]:
x_original[0,0,0] = 0.1113
x_original[0,0,0]

tensor(0.1113)

In [87]:
x_permuted[0,0,0]

tensor(0.1113)

In [88]:
tensor = torch.arange(1,10).reshape(1,3,3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [89]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [90]:
tensor[0,0]

tensor([1, 2, 3])

In [91]:
tensor[0,0,0]

tensor(1)

In [93]:
tensor[0][1][2]

tensor(6)

In [94]:
tensor[0,2,1]

tensor(8)

In [99]:
tensor[:,0]

tensor([[1, 2, 3]])

In [100]:
tensor[:,1]

tensor([[4, 5, 6]])

In [102]:
tensor[:,:,1]

tensor([[2, 5, 8]])

In [103]:
tensor[:,1,1]

tensor([5])

In [105]:
print(tensor[0,2,2])
print(tensor[0,:,2])

tensor(9)
tensor([3, 6, 9])


In [106]:
import numpy as np
import torch

In [109]:
array = np.arange(1,8)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [116]:
torch_tensor = torch.ones(10)
np_array = torch_tensor.numpy()
np_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [117]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8328, 0.5979, 0.6044, 0.4256],
        [0.9415, 0.4788, 0.6413, 0.7520],
        [0.8393, 0.6853, 0.9701, 0.7196]])
tensor([[0.9440, 0.3003, 0.9510, 0.4242],
        [0.9308, 0.8146, 0.5386, 0.7420],
        [0.9123, 0.5095, 0.8207, 0.9182]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [119]:
torch.manual_seed(42)

torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])