In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import torch

### Intro to tensors

In [5]:
scalar = torch.tensor(7)
scalar

tensor(15)

In [12]:
vector = torch.tensor([1,2,3,4])

In [14]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([4])

In [28]:
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6],])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX.shape

torch.Size([2, 3])

In [22]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

In [30]:
torch.rand(3,4)

tensor([[0.3780, 0.7557, 0.5456, 0.5907],
        [0.3773, 0.4754, 0.1180, 0.5692],
        [0.5121, 0.7520, 0.8138, 0.9224]])

In [31]:
torch.rand(10,10)

tensor([[0.8676, 0.8503, 0.0460, 0.6964, 0.6360, 0.9954, 0.8289, 0.6899, 0.2332,
         0.1851],
        [0.9016, 0.3272, 0.5812, 0.9826, 0.6090, 0.3194, 0.5472, 0.1793, 0.3231,
         0.2149],
        [0.5698, 0.2963, 0.3490, 0.2088, 0.8632, 0.5403, 0.3140, 0.7786, 0.2761,
         0.1054],
        [0.4991, 0.7377, 0.3008, 0.0420, 0.0289, 0.0244, 0.5829, 0.8434, 0.5984,
         0.1991],
        [0.2363, 0.2548, 0.8196, 0.3247, 0.9924, 0.4338, 0.9047, 0.7673, 0.1870,
         0.6125],
        [0.3988, 0.4942, 0.3008, 0.4035, 0.6472, 0.6378, 0.5784, 0.8428, 0.8817,
         0.0416],
        [0.6805, 0.6855, 0.5299, 0.2785, 0.6398, 0.8900, 0.8213, 0.5022, 0.8754,
         0.5188],
        [0.1358, 0.5500, 0.0183, 0.5860, 0.6700, 0.4211, 0.0691, 0.6989, 0.2257,
         0.3245],
        [0.4111, 0.3127, 0.9383, 0.8683, 0.8218, 0.0863, 0.8437, 0.8217, 0.4759,
         0.7127],
        [0.2923, 0.1143, 0.2489, 0.4074, 0.7517, 0.2802, 0.6523, 0.1875, 0.5075,
         0.2164]])

In [32]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.4390, 0.6478, 0.6786],
         [0.2533, 0.9400, 0.9723],
         [0.5961, 0.7271, 0.4067],
         ...,
         [0.7683, 0.4448, 0.1706],
         [0.6531, 0.4791, 0.5795],
         [0.1033, 0.4032, 0.6065]],

        [[0.4428, 0.7940, 0.8306],
         [0.8835, 0.5910, 0.0931],
         [0.8929, 0.8038, 0.0720],
         ...,
         [0.9143, 0.5291, 0.4374],
         [0.7677, 0.5128, 0.8116],
         [0.1360, 0.3823, 0.0625]],

        [[0.2156, 0.4764, 0.4530],
         [0.6441, 0.8799, 0.8511],
         [0.7156, 0.1760, 0.6059],
         ...,
         [0.1054, 0.8091, 0.5867],
         [0.2452, 0.3303, 0.5345],
         [0.0288, 0.0390, 0.9754]],

        ...,

        [[0.4640, 0.4620, 0.2975],
         [0.6823, 0.4246, 0.6237],
         [0.5298, 0.3422, 0.7147],
         ...,
         [0.4658, 0.9202, 0.3903],
         [0.6957, 0.7546, 0.7635],
         [0.8294, 0.9470, 0.1084]],

        [[0.4244, 0.5493, 0.8855],
         [0.7232, 0.6098, 0.8831],
         [0.

In [35]:
torch.zeros(size=(4,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [37]:
torch.ones(size=(5,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [40]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [53]:
one_to_twenty = torch.arange(1,21,1)

In [57]:
torch.rand_like(one_to_twenty,dtype=torch.float)

tensor([0.4523, 0.4682, 0.6402, 0.6285, 0.2633, 0.8255, 0.5081, 0.6619, 0.7425,
        0.4254, 0.5185, 0.6577, 0.2935, 0.3122, 0.5453, 0.0024, 0.8257, 0.8312,
        0.1194, 0.8793])